In [1]:
from google.colab import drive
import os
import cv2 
import numpy as np 
import matplotlib.pyplot as plt
import tensorflow as tf
import pickle 
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from sklearn.model_selection import train_test_split

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
fail_ = os.listdir("/content/drive/MyDrive/CV/Fail")
suc_ = os.listdir("/content/drive/MyDrive/CV/Suc")
print('성공 : {} 실패 : {}'.format(len(suc_),len(fail_)))

성공 : 457 실패 : 316


### 이미지 테스트 


In [ ]:
#한개 이미지 테스트
# path = "/content/drive/MyDrive/CV/Suc/" + suc_[0]
# #사이즈 변경후 로드
# target_size = (224, 224)
# img = load_img(path,color_mode = "grayscale", target_size=target_size)
# plt.imshow(img, cmap='gray')
# img = img_to_array(img)
# img.shape

### 데이터 셋 만들기


In [ ]:
target_size = (224, 224)
temp_x = []


# X 라벨 가져오기 
for i in range(len(suc_)):
    path = "/content/drive/MyDrive/CV/Suc/" + suc_[i]
    img = load_img(path,color_mode = "grayscale", target_size=target_size)
    img = img_to_array(img)
    temp_x.append(img)

for j in range(len(fail_)):
    path = "/content/drive/MyDrive/CV/Fail/" + fail_[j]

    img = load_img(path,color_mode = "grayscale", target_size=target_size)
    img = img_to_array(img)
    temp_x.append(img)

# y 라벨 가져오기 
y = [] 
for _ in range(len(suc_)):
  y.append(1)
for _ in range(len(fail_)):
  y.append(0)

train_x = np.array(temp_x)
y_ = [y]
train_y = np.array(y)

In [ ]:
train_x.shape, train_y.shape

((773, 224, 224, 1), (773,))

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(train_x, train_y, test_size = 0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((618, 224, 224, 1), (155, 224, 224, 1), (618,), (155,))

### VGG model

In [ ]:
from tensorflow.keras.layers import Convolution2D, ZeroPadding2D, MaxPooling2D, Flatten, Activation, Dropout
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import models
from tensorflow.keras.models import save_model

In [ ]:
# #VGG-Face model
# model = Sequential()
# model.add(ZeroPadding2D((1,1),input_shape=( 224,224, 1)))
# model.add(Convolution2D(64, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(64, (3, 3), activation='relu'))
# model.add(MaxPooling2D((2,2), strides=(2,2)))
 
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(128, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(128, (3, 3), activation='relu'))
# model.add(MaxPooling2D((2,2), strides=(2,2)))
 
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(256, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(256, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(256, (3, 3), activation='relu'))
# model.add(MaxPooling2D((2,2), strides=(2,2)))
 
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(512, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(512, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(512, (3, 3), activation='relu'))
# model.add(MaxPooling2D((2,2), strides=(2,2)))
 
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(512, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(512, (3, 3), activation='relu'))
# model.add(ZeroPadding2D((1,1)))
# model.add(Convolution2D(512, (3, 3), activation='relu'))
# model.add(MaxPooling2D((2,2), strides=(2,2)))
 
# model.add(Convolution2D(4096, (7, 7), activation='relu'))
# model.add(Dropout(0.5))
# model.add(Convolution2D(4096, (1, 1), activation='relu'))
# model.add(Dropout(0.5))
# model.add(Convolution2D(2622, (1, 1)))
# model.add(Flatten())
# model.add(Activation('softmax'))

In [ ]:
# model.summary()

In [ ]:
# model.load_weights('/content/drive/MyDrive/model/vgg_face_weights.h5')

In [ ]:
# model.layers[-1].output

<KerasTensor: shape=(None, 2622) dtype=float32 (created by layer 'activation')>

In [ ]:
# model.layers[-4].output

<KerasTensor: shape=(None, 1, 1, 4096) dtype=float32 (created by layer 'dropout_1')>

In [ ]:
# model.trainable

True

In [ ]:
# model.weights

In [ ]:
# for layer in model.layers[:-7]:
#     layer.trainable = False

# base_model_output = Sequential()
# base_model_output = Convolution2D(2, (1, 1), name='predictions')(model.layers[-4].output)
# base_model_output = Flatten()(base_model_output)
# base_model_output = Activation('softmax')(base_model_output)
 
# soccer_model = Model(inputs=model.input, outputs=base_model_output)

In [ ]:
# soccer_model.summary()

In [ ]:
# soccer_model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# soccer_model.fit(x_train, y_train, epochs= 20)

In [ ]:
# temp = x_test[5].reshape(1,224,224,1)

In [ ]:
# soccer_model.evaluate(x_test, y_test)

3/3 [==============================] - 1s 174ms/step - loss: 0.6744 - accuracy: 0.5679


[0.6744195222854614, 0.5679012537002563]

In [ ]:
# soccer_model.predict(temp)

1/1 [==============================] - 0s 32ms/step


array([[0.33019558, 0.66980445]], dtype=float32)

In [ ]:
# save_model(soccer_model, "/content/drive/MyDrive/model")

In [ ]:
!pip install deepface

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 KB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 KB 12.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 62.6 MB/s eta 0:00:00
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116952 sha256=0f335b9089f1130047cea79fe66398ae2e0cf6dc02ca5eec194bd8beea208ed9
  Stored in directory: /root/.cache/pip/wheels/f7/f1/89/b9ea2bf8f80ec027a88fef1d354b3816b4d3d29530988972f6
Successfully built fire


In [ ]:
# %run /content/drive/MyDrive/model_weigth/Facenet.py

In [ ]:
# model = InceptionResNetV2()

In [ ]:
# model.load_weights("/content/drive/MyDrive/model_weigth/facenet_weights.h5")

In [ ]:
# # for layer in model.layers[:-8]:
#     layer.trainable = False

# base_model_output = Sequential()
# base_model_output = Convolution2D(2, (2, 2), name='predictions')(model.layers[-5].output)
# base_model_output = Convolution2D(2, (2, 2), name='predictions1')(base_model_output)

# base_model_output = Flatten()(base_model_output)
# base_model_output = Activation('softmax')(base_model_output)
 
# soccer_model1 = Model(inputs=model.input, outputs=base_model_output)

In [ ]:
# soccer_model1.summary()

In [ ]:
# soccer_model.summary()

In [ ]:
# soccer_model1.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# soccer_model1.fit(x_train, y_train, epochs= 20)

Epoch 1/20
10/10 [==============================] - 5s 435ms/step - loss: 0.4660 - accuracy: 0.7750
Epoch 2/20
10/10 [==============================] - 3s 340ms/step - loss: 0.1550 - accuracy: 0.9344
Epoch 3/20
10/10 [==============================] - 3s 343ms/step - loss: 0.0665 - accuracy: 0.9844
Epoch 4/20
10/10 [==============================] - 4s 388ms/step - loss: 0.0341 - accuracy: 0.9969
Epoch 5/20
10/10 [==============================] - 4s 360ms/step - loss: 0.0264 - accuracy: 0.9969
Epoch 6/20
10/10 [==============================] - 3s 344ms/step - loss: 0.0161 - accuracy: 1.0000
Epoch 7/20
 2/10 [=====>........................] - ETA: 2s - loss: 0.0135 - accuracy: 1.0000

KeyboardInterrupt: ignored

In [ ]:
# target_size = (160, 160)
# path = "/content/drive/MyDrive/CV/Suc/" + suc_[0]
# # img = load_img(path, target_size=target_size)

In [ ]:
# img = img_to_array(img)
# img.shape

(160, 160, 3)

In [ ]:
#RGB로 불러오기 
# temp_x = []
# for i in range(len(suc_)):
#   path = "/content/drive/MyDrive/CV/Suc/" + suc_[i]



#   img = load_img(path, target_size=target_size)
#   img = img_to_array(img)
#   temp_x.append(img)

# for j in range(len(fail_)):
#   path = "/content/drive/MyDrive/CV/Fail/" + fail_[j]

#   img = load_img(path, target_size=target_size)
#   img = img_to_array(img)
#   temp_x.append(img)


# train_x = np.array(temp_x)



In [ ]:
# x_train, x_test  , y_train, y_test = train_test_split(train_x, train_y, test_size = 0.2)

In [ ]:
# soccer_model1.fit(x_train, y_train, epochs= 20)

In [ ]:
# tf.config.experimental_run_functions_eagerly(True)

Instructions for updating:
Use `tf.config.run_functions_eagerly` instead of the experimental version.


In [ ]:
# soccer_model1.evaluate(x_test, y_test)

3/3 [==============================] - 1s 401ms/step - loss: 0.6743 - accuracy: 0.7654


[0.6743119955062866, 0.7654321193695068]

In [ ]:
# soccer_model.predict(temp)

1/1 [==============================] - 0s 32ms/step


array([[0.33019558, 0.66980445]], dtype=float32)

In [ ]:
# temp = x_test[20].reshape(1,160,160,3)

In [ ]:
# soccer_model1.predict(x_test, y_test)

1/1 [==============================] - 1s 717ms/step


array([[0.08952615, 0.9104738 ]], dtype=float32)

In [ ]:
y_prob = soccer_model1.predict(temp)
# y_classes = y_prob.argmax(axis=-1)

/usr/local/lib/python3.9/dist-packages/tensorflow/python/data/ops/structured_function.py:256: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(


1/1 [==============================] - 0s 306ms/step


In [ ]:
# img = load_img("/content/drive/MyDrive/CV/12345.png",color_mode = "grayscale", target_size=(224,224))

In [ ]:
# img = np.array(img)

In [ ]:
# x_1 = np.array([img])
# # x_1 = x_1.reshape(1,224,224,1)

In [ ]:
# soccer_model.predict(x_1)

1/1 [==============================] - 0s 42ms/step


array([[0.3419349, 0.6580651]], dtype=float32)

In [ ]:
# soccer_model1.predict(x_1)

1/1 [==============================] - 0s 203ms/step


array([[0.2554469, 0.744553 ]], dtype=float32)

In [ ]:
y_classes

array([1])

In [ ]:
# save_model(soccer_model1, "/content/drive/MyDrive/model2")

In [ ]:
import os
import bz2
import gdown
import numpy as np
from deepface.commons import functions

# pylint: disable=too-few-public-methods


class DlibResNet:
    def __init__(self):

        # this is not a must dependency
        import dlib  # 19.20.0

        self.layers = [DlibMetaData()]

        # ---------------------

        home = functions.get_deepface_home()
        weight_file = home + "/.deepface/weights/dlib_face_recognition_resnet_model_v1.dat"

        # ---------------------

        # download pre-trained model if it does not exist
        if os.path.isfile(weight_file) != True:
            print("dlib_face_recognition_resnet_model_v1.dat is going to be downloaded")

            file_name = "dlib_face_recognition_resnet_model_v1.dat.bz2"
            url = f"http://dlib.net/files/{file_name}"
            output = f"{home}/.deepface/weights/{file_name}"
            gdown.download(url, output, quiet=False)

            zipfile = bz2.BZ2File(output)
            data = zipfile.read()
            newfilepath = output[:-4]  # discard .bz2 extension
            with open(newfilepath, "wb") as f:
                f.write(data)

        # ---------------------

        model = dlib.face_recognition_model_v1(weight_file)
        self.__model = model

        # ---------------------

        # return None  # classes must return None

    def predict(self, img_aligned):

        # functions.detectFace returns 4 dimensional images
        if len(img_aligned.shape) == 4:
            img_aligned = img_aligned[0]

        # functions.detectFace returns bgr images
        img_aligned = img_aligned[:, :, ::-1]  # bgr to rgb

        # deepface.detectFace returns an array in scale of [0, 1]
        # but dlib expects in scale of [0, 255]
        if img_aligned.max() <= 1:
            img_aligned = img_aligned * 255

        img_aligned = img_aligned.astype(np.uint8)

        model = self.__model

        img_representation = model.compute_face_descriptor(img_aligned)

        img_representation = np.array(img_representation)
        img_representation = np.expand_dims(img_representation, axis=0)

        return img_representation


class DlibMetaData:
    def __init__(self):
        self.input_shape = [[1, 150, 150, 3]]

In [ ]:
!git clone https://github.com/serengil/deepface.git

Cloning into 'deepface'...
remote: Enumerating objects: 3933, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 3933 (delta 0), reused 3 (delta 0), pack-reused 3928
Receiving objects: 100% (3933/3933), 49.61 MiB | 37.11 MiB/s, done.
Resolving deltas: 100% (2427/2427), done.


In [ ]:
models = [
  "VGG-Face", 
  "Facenet", 
  "Facenet512", 
  "OpenFace", 
  "DeepFace", 
  "DeepID", 
  "ArcFace", 
  "Dlib", 
  "SFace",
]

#face verification
result = DeepFace.verify(img1_path = "img1.jpg", 
      img2_path = "img2.jpg", 
      model_name = models[0]
)

#face recognition
dfs = DeepFace.find(img_path = "img1.jpg",
      db_path = "C:/workspace/my_db", 
      model_name = models[1]
)

#embeddings
embedding_objs = DeepFace.represent(img_path = "img.jpg", 
      model_name = models[2]
)

NameError: ignored